name: PR Validation

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "docs/**"

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  Validate:
    uses: skyhaven-ltd/pipeline-engineering-github-actions/.github/workflows/reusable-terraform.yml@patch/infracost-cost-only # TEMP: test cost-only Infracost action
    with:
      environments: '["prd"]'
      enable_infracost: false
    secrets: inherit
