name: Tag

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions: {}

jobs:
  Tag:
    permissions:
      contents: write
    uses: skyhaven-ltd/pipeline-engineering-github-actions/.github/workflows/reusable-tag.yml@35c3928dd1e653238dc0de99c8658c916c703a1b # v1.0.1
